--- #YAML:1.0
name:     Math-Algebra-Symbols
version:  1.15
abstract: Symbolic Manipulation using Perl
license:  perl
distribution_type: module
requires:
  Math::BigInt: 0
  Carp:         0
  Scalar::Util: 0
  IO::Handle:   0
recommends:
build_requires:
dynamic_config: 0
