--- #YAML:1.0
name:     Math-Algebra-Symbols
version:  1.21
abstract: Symbolic Algebra in Pure Perl
license:  perl
distribution_type: module
requires:
recommends:
build_requires:
dynamic_config: 0
