--- #YAML:1.0
name:     Math-Algebra-Symbols
version:  1.12
abstract: Symbolic Manipulation using Perl
license:  perl
distribution_type: module
requires:
recommends:
  Math::BigInt: 0
build_requires:
dynamic_config: 0
